51:37:04.866539 USBPROXY Log continuation - Log started 2022-08-11T21:45:04.081106700Z
51:37:04.934247 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#5&39b8775f&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
51:37:04.974574 USBPROXY usbLibGetDevices: Found 4 USB devices, 0 captured
51:37:06.763663 dns-monitor HostDnsMonitor: updating information
51:37:06.763703 dns-monitor HostDnsMonitor: unchanged
51:37:07.276791 USBPROXY usbLibGetDevices: Starting USB device enumeration
51:37:07.345189 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#5&39b8775f&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
51:37:07.405044 USBPROXY usbLibGetDevices: Found 4 USB devices, 0 captured
51:37:14.702799 USBPROXY usbLibGetDevices: Starting USB device enumeration
51:37:14.721078 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#5&2524570b&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
51:37:14.771124 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#5&39b8775f&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
51:37:14.815774 USBPROXY usbLibGetDevices: Found 4 USB devices, 0 captured
51:37:16.483042 USBPROXY usbLibGetDevices: Starting USB device enumeration
51:37:16.501580 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#5&2524570b&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
51:37:16.551107 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#5&39b8775f&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
51:37:16.611918 USBPROXY usbLibGetDevices: Found 4 USB devices, 0 captured
51:37:18.119041 USBPROXY usbLibGetDevices: Starting USB device enumeration
51:37:18.188177 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#5&39b8775f&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
51:37:18.247355 USBPROXY usbLibGetDevices: Found 4 USB devices, 0 captured
51:37:19.296203 USBPROXY usbLibGetDevices: Starting USB device enumeration
51:37:19.365163 USBPROXY Getting USB descriptor (id 0) failed (dwErr=31) on hub USB#ROOT_HUB30#5&39b8775f&0&0#{f18a0e88-c30c-11d0-8815-00a0c906bed8} port 3
51:37:19.407843 USBPROXY usbLibGetDevices: Found 4 USB devices, 0 captured
51:37:27.829821          Saving settings file "C:\Users\amrit\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
51:37:27.853354          Saving settings file "C:\Users\amrit\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
51:37:27.856406          Saving settings file "C:\Users\amrit\.VirtualBox\VirtualBox.xml" with version "1.12-windows"
51:37:33.354357 main     VirtualBox: object deletion starts
51:37:33.354910 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={ad47ad09-787b-44ab-b343-a082a3f2dfb1} aComponent={MediumWrap} aText={Medium 'C:\Users\amrit\VirtualBox VMs\Ubuntu\Ubuntu.vdi' cannot be closed because it is still attached to 1 virtual machines}, preserve=false aResultDetail=0
51:37:33.356696 main     HostDnsMonitor: shutting down ...
51:37:33.356713 main     HostDnsMonitor: shut down
51:37:33.357965 Watcher  ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={d0a0163f-e254-4e5b-a1f2-011cf991c38d} aComponent={VirtualBoxWrap} aText={The object is not ready}, preserve=false aResultDetail=0
51:37:33.358267 main     VirtualBox: object deleted
